/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.servicios.CuentaBancariaServicio;
import controlador.servicios.PersonaServicio;
import controlador.utilidades.Sesion;

/**
 *
 * @author Fabricio
 */
public class FrmDatosCuenta extends javax.swing.JDialog {
    private CuentaBancariaServicio cbs = new CuentaBancariaServicio();
    private PersonaServicio ps = new PersonaServicio();
    /**
     * Creates new form FrmDatosCuenta
     * @param parent componente awt
     * @param modal boolean 
     */
    public FrmDatosCuenta(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        cargarDatos();
    }
    private void cargarDatos(){
    ps.fijarPersona(Sesion.getCuenta().getPersona());
    cbs.fijarCuentaBancaria(Sesion.getCuenta().getPersona().getCuentaBancaria());
    txt_nomb.setText(ps.getPersona().toString());
    txt_nrocuenta.setText(cbs.getCuentaBancaria().getNumerodeCuenta());
    txt_telef.setText(ps.getPersona().getTelefono());
    txt_correo.setText(ps.getPersona().getCorreo());
    txt_cedula.setText(ps.getPersona().getCedula());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        txt_nomb = new javax.swing.JTextField();
        txt_nrocuenta = new javax.swing.JTextField();
        txt_telef = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_correo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_cedula = new javax.swing.JTextField();
        btn_volver = new javax.swing.JToggleButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("MS UI Gothic", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("CUENTA BANCARIA");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(180, 10, 171, 19);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Nombres y Apellidos");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 60, 140, 17);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("N° de Cuenta");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 100, 93, 17);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("N° de Telefono");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 140, 103, 17);
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(30, 280, 500, 10);

        txt_nomb.setEditable(false);
        txt_nomb.setBackground(new java.awt.Color(255, 255, 255));
        txt_nomb.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_nomb.setBorder(null);
        getContentPane().add(txt_nomb);
        txt_nomb.setBounds(250, 60, 280, 17);

        txt_nrocuenta.setEditable(false);
        txt_nrocuenta.setBackground(new java.awt.Color(255, 255, 255));
        txt_nrocuenta.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_nrocuenta.setBorder(null);
        getContentPane().add(txt_nrocuenta);
        txt_nrocuenta.setBounds(250, 100, 280, 17);

        txt_telef.setEditable(false);
        txt_telef.setBackground(new java.awt.Color(255, 255, 255));
        txt_telef.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_telef.setBorder(null);
        getContentPane().add(txt_telef);
        txt_telef.setBounds(250, 140, 280, 17);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Correo Electronico");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(40, 180, 128, 17);

        txt_correo.setEditable(false);
        txt_correo.setBackground(new java.awt.Color(255, 255, 255));
        txt_correo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_correo.setBorder(null);
        txt_correo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_correoActionPerformed(evt);
            }
        });
        getContentPane().add(txt_correo);
        txt_correo.setBounds(250, 180, 280, 17);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Cedula");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(40, 220, 47, 17);

        txt_cedula.setEditable(false);
        txt_cedula.setBackground(new java.awt.Color(255, 255, 255));
        txt_cedula.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_cedula.setBorder(null);
        getContentPane().add(txt_cedula);
        txt_cedula.setBounds(250, 220, 280, 17);

        btn_volver.setBackground(new java.awt.Color(153, 153, 255));
        btn_volver.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_volver.setText("Volver");
        btn_volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_volverActionPerformed(evt);
            }
        });
        getContentPane().add(btn_volver);
        btn_volver.setBounds(250, 310, 71, 25);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(30, 40, 500, 10);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/img/asd.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 570, 370);

        setSize(new java.awt.Dimension(586, 409));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_correoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_correoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_correoActionPerformed

    private void btn_volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_volverActionPerformed
        new FrmPrincipal().setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_volverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmDatosCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmDatosCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmDatosCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmDatosCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrmDatosCuenta dialog = new FrmDatosCuenta(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btn_volver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField txt_cedula;
    private javax.swing.JTextField txt_correo;
    private javax.swing.JTextField txt_nomb;
    private javax.swing.JTextField txt_nrocuenta;
    private javax.swing.JTextField txt_telef;
    // End of variables declaration//GEN-END:variables
}
