/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.JFrame;
import javax.swing.UIManager;

/**
 *
 * @author Fabricio
 */
public class FrmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_cuentaBancaria = new javax.swing.JButton();
        btn_solicitarPrestamo = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btn_salirPrincipal = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        btn_cuentaBancaria.setFont(new java.awt.Font("MS UI Gothic", 0, 12)); // NOI18N
        btn_cuentaBancaria.setForeground(new java.awt.Color(0, 102, 153));
        btn_cuentaBancaria.setText("Cuenta Bancaria");
        btn_cuentaBancaria.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_cuentaBancaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cuentaBancariaActionPerformed(evt);
            }
        });
        getContentPane().add(btn_cuentaBancaria);
        btn_cuentaBancaria.setBounds(20, 110, 120, 30);

        btn_solicitarPrestamo.setFont(new java.awt.Font("MS UI Gothic", 0, 12)); // NOI18N
        btn_solicitarPrestamo.setForeground(new java.awt.Color(0, 102, 153));
        btn_solicitarPrestamo.setText("Solicitar Prestamo");
        btn_solicitarPrestamo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_solicitarPrestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_solicitarPrestamoActionPerformed(evt);
            }
        });
        getContentPane().add(btn_solicitarPrestamo);
        btn_solicitarPrestamo.setBounds(20, 70, 120, 30);

        jButton1.setFont(new java.awt.Font("MS UI Gothic", 0, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 102, 153));
        jButton1.setText("Pagos");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(20, 150, 120, 30);

        btn_salirPrincipal.setFont(new java.awt.Font("MS UI Gothic", 0, 12)); // NOI18N
        btn_salirPrincipal.setForeground(new java.awt.Color(0, 102, 153));
        btn_salirPrincipal.setText("Salir");
        btn_salirPrincipal.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_salirPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirPrincipalActionPerformed(evt);
            }
        });
        getContentPane().add(btn_salirPrincipal);
        btn_salirPrincipal.setBounds(20, 210, 70, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/img/Tío_Rico.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(80, 10, 305, 365);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(20, 190, 120, 10);

        setSize(new java.awt.Dimension(411, 426));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_salirPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirPrincipalActionPerformed
        // TODO add your handling code here:
        new FrmLogin(this,true).setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_salirPrincipalActionPerformed

    private void btn_solicitarPrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_solicitarPrestamoActionPerformed
        // TODO add your handling code here:
        new FrmPrestamos(this,true).setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_solicitarPrestamoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new FrmPagos(this,true).setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn_cuentaBancariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cuentaBancariaActionPerformed
     new FrmCuentaBancaria(this,true).setVisible(true);
     dispose();
    }//GEN-LAST:event_btn_cuentaBancariaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
JFrame.setDefaultLookAndFeelDecorated(true);
        try {
            // select Look and Feel
            UIManager.setLookAndFeel("com.jtattoo.plaf.mint.MintLookAndFeel");
            // start application
           ;
        }
        catch (Exception ex) {
            ex.printStackTrace();
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cuentaBancaria;
    private javax.swing.JButton btn_salirPrincipal;
    private javax.swing.JButton btn_solicitarPrestamo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
