/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.servicios.PersonaServicio;
import controlador.utilidades.Sesion;
import javax.swing.JFrame;
import javax.swing.UIManager;

/**
 *
 * @author Fabricio
 */
public class FrmPrincipal extends javax.swing.JFrame {
private PersonaServicio ps = new PersonaServicio();
    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
        initComponents();
        cargarDatos();
        cargarRol();
    }
    private void cargarRol(){
    if(Sesion.getCuenta().getPersona().getRol().getNombre().toLowerCase().trim().equals("administrador")){
        btn_admin.setVisible(true);
        }
        else if(Sesion.getCuenta().getPersona().getRol().getNombre().toLowerCase().trim().equals("usuario")){
        btn_admin.setVisible(false);
        }
    }
    private void cargarDatos(){
    ps.fijarPersona(Sesion.getCuenta().getPersona());
    jl_usuario.setText(ps.getPersona().toString());
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btn_cuenta = new javax.swing.JToggleButton();
        btn_prestamo = new javax.swing.JToggleButton();
        btn_cerrar = new javax.swing.JToggleButton();
        jLabel2 = new javax.swing.JLabel();
        jl_usuario = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        btn_admin = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/img/user.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 130, 129);

        btn_cuenta.setText("Su Cuenta");
        btn_cuenta.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btn_cuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cuentaActionPerformed(evt);
            }
        });
        jPanel1.add(btn_cuenta);
        btn_cuenta.setBounds(20, 200, 100, 30);

        btn_prestamo.setText("Solicitar un Prestamo");
        btn_prestamo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btn_prestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_prestamoActionPerformed(evt);
            }
        });
        jPanel1.add(btn_prestamo);
        btn_prestamo.setBounds(20, 240, 140, 30);

        btn_cerrar.setBackground(new java.awt.Color(255, 255, 255));
        btn_cerrar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn_cerrar.setText("Cerrar Sesion");
        btn_cerrar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btn_cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cerrarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_cerrar);
        btn_cerrar.setBounds(20, 140, 90, 20);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("BIENVENID@");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(150, 30, 110, 22);

        jl_usuario.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(jl_usuario);
        jl_usuario.setBounds(150, 60, 140, 30);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/img/images-1-2.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(230, 90, 230, 200);

        jToggleButton1.setText("Registro de Prestamos");
        jToggleButton1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton1);
        jToggleButton1.setBounds(20, 280, 140, 30);

        btn_admin.setText("Administrar persona");
        btn_admin.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btn_admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_adminActionPerformed(evt);
            }
        });
        jPanel1.add(btn_admin);
        btn_admin.setBounds(270, 290, 180, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 560, 330);

        setSize(new java.awt.Dimension(576, 370));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_prestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_prestamoActionPerformed
        new FrmPrestamos(this,true).setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_prestamoActionPerformed

    private void btn_cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cerrarActionPerformed
        new FrmLogin(this,true).setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_cerrarActionPerformed

    private void btn_cuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cuentaActionPerformed
        new FrmDatosCuenta(this,true).setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_cuentaActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        new FrmRegistroPrestamos(this,true).setVisible(true);
        dispose();
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void btn_adminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_adminActionPerformed
         new FrmPersonas(this,true).setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_adminActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
JFrame.setDefaultLookAndFeelDecorated(true);
        try {
            // select Look and Feel
            UIManager.setLookAndFeel("com.jtattoo.plaf.mint.MintLookAndFeel");
            // start application
           ;
        }
        catch (Exception ex) {
            ex.printStackTrace();
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btn_admin;
    private javax.swing.JToggleButton btn_cerrar;
    private javax.swing.JToggleButton btn_cuenta;
    private javax.swing.JToggleButton btn_prestamo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel jl_usuario;
    // End of variables declaration//GEN-END:variables
}
